### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by nobl** [StrathCole/ioBroker.plenticore#13]
With latest changes to iobroker, adapter is throwing this warning several times:

> adapter.objects.getObjectView  is deprecated, and will be removed in the future. Please use  adapter.getObjectView/Async. Report this to Developer!

Further: Travis fails on node.js 8 testing - but that is due to changes in iobroker and 8 is removed from adapter templates meanwhile anyways.

Going to send a pull request (if you want to accept it). 
Works here for me and travis is also ok with it.

**Comment by StrathCole** [comment]
Thank you. Fixed by #14
