### ISSUE TITLE
Using Plenticore Adapter only for forecast

### ISSUE THREAD

**Issue by kaybau** [StrathCole/ioBroker.plenticore#15]
Hello,
I have a Kostal BA inverter which is connected via Javascript to iobroker.
I want to use your adapter for forecast reasons, 
Is there any chance to deactivate the polling to Plenticore address?
beside of Plenticore adapter I have daswetter. Where are the datapoints stored for forecast?
under Plenticore/forecast I have 2 DP's. one is website to kachelmann, second DP is my city.

Cheers,
Kay

**Comment by StrathCole** [comment]
No sorry, the polling is needed for the adapter to work. It is not planned to make a forecast-only adapter.

**Comment by StrathCole** [comment]
The datapoints are at `plenticore.forecast.current/day1/day2`.

**Comment by kaybau** [comment]
a pity. forecast data will only be generated, if Plenticore data are available.
