### ISSUE TITLE
EnergyFlow.Yield

### ISSUE THREAD

**Issue by NielsWL** [StrathCole/ioBroker.plenticore#16]
Hey...

The data EnergyFlow.Yield is not the complete yield of the PV-Plant. The energy that is used for charching the battery is missing. Can you add data fields (day, month, year, total) so that all the yield of the plant can be logged?

**Comment by StrathCole** [comment]
> The data EnergyFlow.Yield is not the complete yield of the PV-Plant.

Yes, but that is the way KOSTAL fills the yield field (consistend with KOSTAL and PIKO portal).

The Fields for year, day etc. are available, e. g. `plenticore.0.scb.statistic.EnergyFlow.YieldDay`

**Comment by NielsWL** [comment]
i know...

but can you add it? I can get the data by a blookly script, but maybe you can add it in the adapter directly.

```
var PV_Ertrag1, PV_Ertrag2;
schedule("* * * * * *", function () {
  PV_Ertrag1 = getState("plenticore.0.scb.statistic.EnergyFlow.YieldDay").val;
  PV_Ertrag2 = (typeof PV_Ertrag2 == 'number' ? PV_Ertrag2 : 0) + getState("plenticore.0.devices.local.battery.Charge_P").val / 3600;
  setState("plenticore.0.scb.statistic.EnergyFlow.PVErtrag"/*PVErtrag*/, (PV_Ertrag1 + PV_Ertrag2), true);
  console.log((PV_Ertrag1 + PV_Ertrag2));
});
```

**Comment by StrathCole** [comment]
The problem is that this value is not available from the inverter. I would have to calculate the value myself and it would be more inaccurate the higher the set polling interval in the instance config is.

**Comment by NielsWL** [comment]
ok. then i calculate it with the blockly script. thanks.
