### ISSUE TITLE
Falsche Ortsbestimmung für Kachelmann

### ISSUE THREAD

**Issue by cvastag** [StrathCole/ioBroker.plenticore#17]
Leider wird der Ort bei mir falsch bestimmt

Kachelmann nimmt den Ort lindenberg, ich wohne aber in der Nähe von Wuppertal.
Die Koordinaten in den Haupteinstellungen von IoBroker stimmen

**Comment by StrathCole** [comment]
Hallo, auf die Bestimmung habe ich keinen Einfluss. Diese kommt direkt von der Kachelmann-Webseite. Vermutlich wird dort bei Eingabe der Koordinaten dann auch dieser Ort genommen?
