### ISSUE TITLE
Miss Energyflow from PV to Battery

### ISSUE THREAD

**Issue by mla4ger** [StrathCole/ioBroker.plenticore#19]
Hi,

i miss the Energyflow Energy to Battery. In the inverter portal i can see it. Is it possible to add this?

thanks a lot.

**Comment by StrathCole** [comment]
Hello. It is in `plenticore.0.devices.local.battery.Charge_P`, `plenticore.0.devices.local.battery.Discharge_P` and `plenticore.0.devices.local.battery.P`.
