### ISSUE TITLE
Battery information is not updated with Kostal Plenticore SW 011605025

### ISSUE THREAD

**Issue by Nievi01** [StrathCole/ioBroker.plenticore#20]
Since I have installed the new Kostal Plenticore Software "KOSTAL_Update_PLENTICORE_PIKO_IQ_011605025.swu" all Battery values in the adapter are not updated any more  (Plenticore 10 + BYD HV10.2) The Battery values are still shown on the webpage of Plenticore.

**Comment by StrathCole** [comment]
Please stop and re-start the adapter. Also try installing the latest version (r227) from git.
