### ISSUE TITLE
Unterstützung von HTTPs

### ISSUE THREAD

**Issue by KoMa1978** [StrathCole/ioBroker.plenticore#22]
Hi,

es wäre klasse, wenn der Connect zum Wechselrichter wahlweise per HTTP oder HTTPS erfolgen könnte.

Der Einbau als Option dürfte ja relativ einfach sein, da Kostal HTTPs aber sehr stiefmütterlich behandelt, bitte unbedingt daran denken, dass ungültige Zertifikate ignoriert werden (ich vermute die Option ist "rejectUnauthorized: false").

Ansonsten läuft der Adapter hier mit einem Plenticore Plus 10 (Firmware 01.17.05075) auf anhieb und echt gut!!
Du solltest gucken, ob man den nicht in Richtung "stable" bringen kann, damit er im iobroker direkt zum Download angeboten wird.

Besten Dank,
 KoMa

**Comment by StrathCole** [comment]
Ich muss mal schauen, dass ich eine https-Option noch einbinde. Danke für den Hinweis, habe ich für Kostal selbst nie genutzt.

**Comment by KoMa1978** [comment]
Ich versuche so weit es geht, alle Geräte verschlüsselt anzusprechen ... Leider wird dieses Thema seeehr stiefmütterlich behandelt, nicht nur von Kostal, sondern auch von vielen anderen.

Da man leider das https-Zertifikat im WR nicht tauschen kann und das Zertifikat ungültig ist (abgelaufen, auf den Hostnamen SCB, ...) unbedingt ungültige Zertifikate erlauben.

Besten Dank auf jeden Fall schon einmal und wenn was getestet werden soll, melde Dich gerne.

**Comment by StrathCole** [comment]
Ist nun in Version 2.2.0 möglich.
