### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Bernd1984** [StrathCole/ioBroker.plenticore#25]
Hallo,
es scheint, als würde der Adapter gut funktionieren.
Wann wird dieser denn offiziell in den ioBroker aufgenommen?
Vielen Dank & Gruß, Bernd

**Comment by StrathCole** [comment]
Hi, habe aktuell das Problem, dass ich den Travis-Test nicht zum Laufen kriege. Ohne den kann der Adapter nicht eingereicht werden.

**Comment by Bernd1984** [comment]
Hallo Marius, 

danke für deine Antwort.

Ich bin noch sehr neu im Thema ioBroker und habe deine ZipFile in /opt/iobroker/node_modules kopiert bzw. entpackt.

Danach kann ich ihn auch unter Adapter sehen. Leider kann ich ihn dann aber nicht installieren.

Mache ich etwas falsch?

Vielen Dank & beste Grüße, Bernd 

 

Von: Marius Burkard [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. Januar 2021 17:48
An: StrathCole/ioBroker.plenticore <ioBroker.plenticore@noreply.github.com>
Cc: Bernd1984 <bernd.klink.bk@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [StrathCole/ioBroker.plenticore] Release? (#25)

 

Hi, habe aktuell das Problem, dass ich den Travis-Test nicht zum Laufen kriege. Ohne den kann der Adapter nicht eingereicht werden.

**Comment by StrathCole** [comment]
Wenn du noch ein oder zwei Tage wartest, sollte der Adapter in der offiziellen Liste auftauchen. Habe ihn im Stable-Repository eingereicht.
