### ISSUE TITLE
Erweiterung der Eingabe mit einem Port

### ISSUE THREAD

**Issue by psg1** [StrathCole/ioBroker.plenticore#29]
Hallo und vielen Dank für deine tolle Arbeit.

Besteht die Möglichkeit die Eingabe des Ports (anstelle der 80) mit einzubeziehen? Hintergrund ist die Abfrage eines nicht lokalen Wechselrichters, welcher über Portforwarding eine Freigabe hat.

Ich bin die Einstellungen mal händisch durchgegangen und habe dies erfolgreich getestet.

**Comment by StrathCole** [comment]
Grundsätzlich bestimmt. Es ist ja auch angefragt in #22 https zu unterstützen. Wird aber noch etwas dauern.

**Comment by StrathCole** [comment]
Siehe #36 - nun möglich.
