### ISSUE TITLE
Warnings wegen nicht existierendem Objekt

### ISSUE THREAD

**Issue by nobl** [StrathCole/ioBroker.plenticore#31]
Folgende Warnings kommen bei jedem Datenabruf:

(840) State "plenticore.0.forecast.day1.power.4h.generated" has no existing object, this might lead to an error in future versions
(840) State "plenticore.0.forecast.day1.power.4h.generated" has no  existing object, this might lead to an error in future versions
(840) State "plenticore.0.forecast.day1.power.4h.generated" has no  existing object, this might lead to an error in future versions

Dabei ist der Teil "4h" variabel. Mal 1h, 3h, ...
Der betreffende Datenpunkt ist nicht angelegt.

Stoppt man den Adapter, löscht "forecast.day1" komplett und startet den Adapter danach wieder, so wird der Datenpunkt angelegt.
Einen Tag später ist er dann wieder gelöscht und die Warnings trudeln erneut ein.

**Comment by virusbrain** [comment]
Hi, bei mir kann ich das gleiche Verhalten beobachten. Wobei ich meine, dass das erst seit dem Update des JS-Controllers auf 3.2.16 so ist?

**Comment by nobl** [comment]
Hat nichts mit 3.2.16 zu tun, denn meiner läuft noch auf 3.2.12.

**Comment by StrathCole** [comment]
Bitte mal schauen, ob das nach dem Update auf 2.1.8 immer noch ist.

**Comment by nobl** [comment]
Ich habe eben einmal aktualisiert und werde das nun beobachten.
Für den Moment ist erstmal Ruhe - aber das war auch der Fall, hatte man die Datenpunkte alle gelöscht und den Adapter neu gestartet. 

Genaueres dürfte es leider erst morgen oder übermorgen zu vermelden geben. (Im Zweifel kurz anpingen, dann prüfe ich das.)

**Comment by StrathCole** [comment]
> Genaueres dürfte es leider erst morgen oder übermorgen zu vermelden geben. (Im Zweifel kurz anpingen, dann prüfe ich das.)

Danke. Ich versuche auch dran zu denken, bei mir selbst zu schauen. Leider gibt das Log nicht her, an welcher Stelle das Problem auftritt, daher ist es schwer zu debuggen.

**Comment by StrathCole** [comment]
Ich schließe mal, weil es bisher nicht mehr aufgetaucht ist.
