### ISSUE TITLE
Error getting forecast data from met.no api: null

### ISSUE THREAD

**Issue by Seffe-00** [StrathCole/ioBroker.plenticore#32]
Seit heute Morgen werden die Prognose Daten nicht mehr aktualisiert.

Könnte es vielleicht mit dem Update der Metno API zusammenhängen?.

Siehe

https://api.met.no/

News:
Locationforecast and Nowcast
As mentioned previously, the old versions of Locationforecast (1.9), Nowcast (0.9) and Weathericon (1.1) will terminate on March 1st, 2021. Incredibly, almost 70 % of the current API traffic is still using version 1.9, This means a lot of sites and apps will stop working shortly. We recommend everyone not yet upgraded to start working on this ASAP. Please see our docs for more information:

Gruß Seffe

**Comment by StrathCole** [comment]
Danke für den Hinweis. Hatte ich gar nicht mitbekommen.

**Comment by StrathCole** [comment]
Sollte mit neuer Version 2.1.8 behoben sein.

**Comment by Seffe-00** [comment]
Danke für die schnelle Reaktion.

Forecast_Current_Power:

Max wird nun aktualisiert

Jedoch die Werte:
Sky
Skyvis
Skyrain 

werden nicht aktualisiert.

Bei Rain steht bei metno noch

null mm

Kann mich nicht Erinnern ob dies schon immer so war?

Gruß Seffe
