### ISSUE TITLE
Update 2.1.8 Prognose mit Metno V2.0

### ISSUE THREAD

**Issue by Seffe-00** [StrathCole/ioBroker.plenticore#33]
Danke für die schnelle Reaktion.

Forecast_Current_Power:

Max wird nun aktualisiert

Jedoch die Werte:
Sky
Skyvis
Skyrain

werden nicht aktualisiert.

Bei Rain steht bei metno noch

null mm

Kann mich nicht Erinnern ob dies schon immer so war?

Gruß Seffe

**Comment by StrathCole** [comment]
Danke, hatte noch einen Fehler in der Verwendung der neuen API. Ist mit 2.1.9 korrigiert.
