### ISSUE TITLE
ENOTFOUND when starting the adapter

### ISSUE THREAD

**Issue by backupandforkacc** [StrathCole/ioBroker.plenticore#36]
Version I am using: 2.1.6

I am getting these two errors when trying to start the plenticore adapter: 
(5285) Login failed with code 0:  
(5285) API request failed with error {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http://huntworker.ddns.net:81/"}

By firefox, I can access the plenticore frontend.

**Comment by StrathCole** [comment]
Adding a port to the host name is NOT supported currently. Specifying a port will be possible in a future version. So currently the adapter only works when using the default port 80.

**Comment by StrathCole** [comment]
It is now supported (version 2.2.0) to add a custom port.
