### ISSUE TITLE
wrong types with js-controller 3.3.5

### ISSUE THREAD

**Issue by amg666** [StrathCole/ioBroker.plenticore#37]
after update to js-controller 3.35 the plenticore adapter produces lots of infos: I changed log level to warning, to avoid an overload of the logfile...

`plenticore.0 | 2021-05-02 13:36:03.113 | info | State value to set for "plenticore.0.scb.export.Portal" has to be type "number" but received type "string"
-- | -- | -- | --
plenticore.0 | 2021-05-02 13:36:03.111 | info | State value to set for "plenticore.0.scb.export.LastExport" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.110 | info | State value to set for "plenticore.0.scb.modbus.ModbusUnitId" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.097 | info | State value to set for "plenticore.0.devices.local.StateKey0" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.096 | info | State  value to set for "plenticore.0.devices.local.inverter.MaxApparentPower"  has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.095 | info | State value to set for "plenticore.0.devices.local.generator.ShadowMgmt" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.089 | info | State value to set for "plenticore.0.devices.local.EnergySensor" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.089 | info | State value to set for "plenticore.0.devices.local.battery.Type" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.088 | info | State value to set for "plenticore.0.devices.local.battery.SupportedTypes" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.087 | info | State value to set for "plenticore.0.devices.local.battery.Strategy" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.086 | info | State value to set for "plenticore.0.devices.local.battery.MinSoc" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.085 | info | State  value to set for  "plenticore.0.devices.local.battery.MinHomeConsumption" has to be type  "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.083 | info | State value to set for "plenticore.0.devices.local.battery.ExternControl" has to be type "number" but received type "string"
plenticore.0 | 2021-05-02 13:36:03.082 | info | State value to set for "plenticore.0.devices.local.battery.DynamicSoc" has to be type "boolean" but received type "string"

`

**Comment by StrathCole** [comment]
The types have now been fixed in the current git version (r235).
