### ISSUE TITLE
PV power to the grid

### ISSUE THREAD

**Issue by Tramour** [StrathCole/ioBroker.plenticore#4]
Hi,
excellent work and very useful. Two questions: How can I read the power from PV which was sent to the grid? And is there also a possibilty to access the data from a PIKO 3.0-2 plus via API?

**Comment by StrathCole** [comment]
Hi,
you have to calculate the power sent to grid by yourself (PV_P - HOME_P - BATTERY_CHARGE).
Maybe I'll add this to one of the next versions.

The Piko will possibly not work I guess. I have no idea how it works, though.

**Comment by Tramour** [comment]
Okay. Thanks a lot.

**Comment by StrathCole** [comment]
I re-open this to integrate the value(s) directly into the adapter.

**Comment by StrathCole** [comment]
The values for ToGrid_P and the corresponding statistic values are now populated.
