### ISSUE TITLE
After upgrading to latest iobroker with Admin 5 info log with wrong variable declaration

### ISSUE THREAD

**Issue by KoMa1978** [StrathCole/ioBroker.plenticore#43]
Hi,

after upgrading my iobroker to version 3.3.15, I got the following log from plenticore 2.2.0 adapter:

State value to set for "plenticore.0.scb.export.LastExportOk" has to be type "boolean" but received type "number"

KoMa1978

**Comment by StrathCole** [comment]
Please delete the datapoint (state object) `plenticore.0.scb.export.LastExportOk` and restart the adapter. The type has changed. See changelog, please: https://github.com/StrathCole/ioBroker.plenticore#220
