### ISSUE TITLE
LastExportOk

### ISSUE THREAD

**Issue by Bernd1984** [StrathCole/ioBroker.plenticore#53]
Hallo, 
ich bekomme immer wieder die Fehlermeldung im Log:
State value to set for "plenticore.0.scb.export.LastExportOk" has to be type "boolean" but received type "number"
v2.2.0
Viele Grüße,
Bernd

**Comment by StrathCole** [comment]
Hallo. Bitte lösche den entsprechenden Datenpunkt aus dem Objektbaum und lass ihn neu erzeugen (Adapter aus Git installieren und neu starten).
