### ISSUE TITLE
Glätten der Werte in plenticore.0.forecast.day1.power.day_adjusted 

### ISSUE THREAD

**Issue by RePa02** [StrathCole/ioBroker.plenticore#67]
Ich nutze den Wert, um zu entscheiden ob ich noch Strom verschwenden darf oder nicht, Allerdings ergeben sich innerhalb einer Stunde mehrere Schwankungen die meines Erachtens auf einen unglücklichen Rechenweg hindeuten. Lässt sich das vielleicht glätten?
Ich kann mir die Werte zwar auch selbst weg schreiben und glätten, vermute aber das das so nicht gewollt ist.
 
![image](https://user-images.githubusercontent.com/102346031/186399853-9b3520e6-9de0-443b-8c03-d908e55a105c.png)

Vielen Dank.

**Comment by PastCoder** [comment]
Hallo,
welche Version verwendest du? Ist die Änderung von pull request #57 https://github.com/StrathCole/ioBroker.plenticore/pull/57 bereits dabei? Falls nicht, reduziert diese die Schwankung vielleicht schon genug. Ist dann auch nicht ganz weg, aber recht gering.

**Comment by RePa02** [comment]
Ich habe Version 2.2.0 des Adapters. Also ist die Änderung wohl noch nicht eingeflossen. 
Sorry, habe ich nicht gesehen. :( Danke.

**Comment by PastCoder** [comment]
Gerne. Kurze Rückmeldung willkommen, ob das Problem damit gelöst ist.

**Comment by RePa02** [comment]
Ich hab das nun etwas laufen lassen und kann sagen das Problem ist durch die Version 2.2.2 des Adapters gelöst. Die Werte sind weitestgehend geglättet. Super!
