### ISSUE TITLE
plenticore.x.forecast.dayx.power.xh.time not matching full hours

### ISSUE THREAD

**Issue by EvilEls** [StrathCole/ioBroker.plenticore#77]
Hi!
it appears that the `generated` values for the forecast hours `plenticore.0.forecast.dayx.power.xh` are not correct.

![grafik](https://github.com/StrathCole/ioBroker.plenticore/assets/29343914/8edee787-b4b3-4315-949a-1521ebb32d9f)

In the example `plenticore.0.forecast.day1.power.4h.generated` holds the actually generated power between `06:48:46` until `07:48:45`.
At `07:48:46` generated power already counts towards `plenticore.0.forecast.day1.power.5h.generated`.

So it seems, the last 11m14sec of each hour are counted to the following hour.

**Comment by StrathCole** [comment]
Hey. No. This is calculated from sunrise. So 1h is the first hour after sunrise.
