### ISSUE TITLE
Second pv area for forecast

### ISSUE THREAD

**Issue by marcelkrois** [StrathCole/ioBroker.plenticore#8]
Hey, great job, especially the forecast function with edit the min SoC. I have pv area on two roof sides. They are 180 degrees opposite and have different sizes. Is it possible to take the second area into calculating of minimum SoC? 
Best wishes

**Comment by StrathCole** [comment]
Hi, this is already implemented in the current git version on github, but the version is not yet ready to be used due to some bugs and changes in it.
