### ISSUE TITLE
Datenpunkt für bisherigen Ertrag des Tages?

### ISSUE THREAD

**Issue by thoblank** [StrathCole/ioBroker.plenticore#89]
Hallo zusammen,
welcher Datenpunkt zeigt den bisherigen Ertrag des laufenden Tages?
Und falls es den nicht gibt, wie berechnet ihr diesen Wert?

Viele Grüße,
Thomas

**Comment by NielsWL** [comment]
plenticore.0.forecast.current.power.generated

mfg Niels.

Am Di., 24. Okt. 2023 um 13:44 Uhr schrieb thoblank <
***@***.***>:
